### ISSUE TITLE
Faulty test in Linux > environment variables

### ISSUE THREAD

**Issue by tluge** [enkidevs/curriculum#2063]
In the last test (entitled"practice") in manipulating-environment-variables-iii.md, two answers are asked to be given although there is only one command to fill.

**Comment by kapnobatai137** [comment]
Hello @tluge and thanks for the report.

Because some examples might be wider than your phone, we have made codeblocks (and tables) scrollable:

![scrollable-code-block](https://img.enkipro.com/92c495af917c7bf34c01b81847d37c48.gif)

With this said, I can see how the first question gap can be conceived as hidden. I'll update the question to a friendlier formatting.

**Comment by tluge** [comment]
Oh, yes! I didn't notice that you could scroll. Thank you for the quick reply. So far, it's an amazing app! :)
