### ISSUE TITLE
Feat: Add Prettier 

### ISSUE THREAD

**Issue by iamclaytonray** [enkidevs/curriculum#809]
Some of the markdown & JS is kind of wacky. Prettier can clean some of this stuff up automatically. I can shoot over a PR for this if this is accepted!

**Comment by lizTheDeveloper** [comment]
Some of the markdown and JS *is* kind of wacky, but this is partly because of character limits on devices. We're still supporting the older iPhones, so our max width is 44 characters. Lots of our users are in all kinds of places around the world, so many of them are using older tech, which is why we have this line width rule.
We could probably clean up *some* of it automatically, but I have tried to use `standard` to clean it up with some extra configs, and it just makes a giant mess. You're welcome to take a swing at it though, so long as the validators on PRs pass it will work in our system.

**Comment by nem035** [comment]
Hi @iamclaytonray, thanks for the contribution and comments 😄 

Just wanted to mention something. It might not be possible (or at least practical) to use prettier to format our content as a whole because we are using [our own format](https://github.com/enkidevs/curriculum-processors/tree/master/packages/curriculum-parser).

We have to make sure prettier doesn't break our syntax. Since prettier has a very small api surface area (we can't configure the markdown parser), we'd have to do something like fork it to adjust to our content. A positive aspect to this is that prettier is [using](https://github.com/prettier/prettier/blob/master/src/language-markdown/parser-markdown.js#L10) the same parsing libraries as us so interoperability might be easier then it seems but we are using different [settings](https://github.com/enkidevs/curriculum-processors/blob/master/packages/curriculum-compiler-string/plugins/markdown/index.js#L6) (see [remark-stringify](https://www.npmjs.com/package/remark-stringify)). This is why, for example, your [PR](https://github.com/enkidevs/curriculum/pull/818) has all of our italic text between underscores instead of asterisks, i.e. `_abc_` instead of `*abc*`.

Alternative solution could be to just skip the markdown and only format the code snippets. 
One way to achieve this would be to run each insight through the [curriculum parser](https://github.com/enkidevs/curriculum-processors/tree/master/packages/curriculum-parser), visit each `code` node in the generated AST, format its contents through `prettier`, then [compile](https://github.com/enkidevs/curriculum-processors/tree/master/packages/curriculum-compiler-string) the AST back into an insight string.

Of course, this wouldn't be a trivial tak and it might seem like way less fun (and debatable less useful) than [writting about Go](https://github.com/enkidevs/curriculum/issues/810) and adding a whole new topic 😄

**Comment by iamclaytonray** [comment]
Makes sense. I'm going to close this issue and #818
